# Generated by Django 5.2.11 on 2026-02-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_category_unique_category_name_ci'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_ci',
        ),
    ]
