# Generated by Django 5.2.11 on 2026-02-19 09:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('category_name'), name='unique_category_name_ci', violation_error_message='This category already exists. Please choose a different name.'),
        ),
    ]
